### ISSUE TITLE
Recog speed slow and low audio recording quality

### ISSUE THREAD

**Issue by ken-cheng-valon** [ScazLab/ros_speech2text#15]

**Comment by omangin** [comment]
OK. First thing, to track down the bottlenecks in the code, you can use the `%prun` function of ipython to profile the code. (You'll need to run it manually from the interpreter.)

For the sound quality, the issue could come from the conversions from the buffer to numpy or from the type of data we use in all the conversions.

Is the full code slow or just when handling utterances?
A few things to check:
– The line [speech_detection.py#L15](https://github.com/ScazLab/ros_speech2text/blob/master/s2t/speech_detection.py#L15) forces a conversion of the numpy array with int type to float and then back to int. It could lead to the quality issue by scaling the sound too much (you could print the value of `(NORMAL_MAXIMUM * 1. / max(1, np.abs(snd_data).max())` to check if it's not too large) or to the speed issue because of the conversion (in which case we could cast the multiplier into an integer). However, quality-wise, this should not be different from the previous behavior that was using integers to represent the data.
– Maybe the [ros_speech2text_async.py#L45](https://github.com/ScazLab/ros_speech2text/blob/master/scripts/ros_speech2text_async.py#L45) function could be replaced by [`scipy.io.wavefile.write`](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.io.wavfile.write.html).
– Double check that the right sample rate is used on read and write.
– Can you upload a file with quality issues?

**Comment by ken-cheng-valon** [comment]
Solved by changing audio rate and chunk size
